# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: PS, codes.
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Zen Antique
    code: Azaret Mono
  logo: assets/PS_solid.png
  favicon: assets/PS_clear.png
  features:
    - navigation.tracking
  icon:
    repo: fontawesome/brands/git-square
plugins:
  - search
repo_url: https://github.com/peterschutt/peterschutt.github.io
markdown_extensions:
  - admonition
